{{- include "wildfly-common.detect.deployment.type" . }}

{{- if (and .Values.deploy.enabled .Values.deploy.useDeployment)}}
{{- include "wildfly-common.deployment" (list . "wildfly.deployment") -}}
{{- end -}}

{{ define "wildfly.deployment" }}
{{- include "wildfly.deployment.labels" . }}
spec:
  template:
    {{- include "wildfly.deployment.labels" . | nindent 4 }}
{{- end -}}