image:
  tag: latest
build:
  enabled: true
  mode: s2i
  bootableJar:
    builderImage: registry.access.redhat.com/ubi8/openjdk-11:latest
  s2i:
    # temporary overriding to use the S2I images from the jdenise org
    # before they are pushed to the wildlfy org.
    version: latest
    # builderImage: quay.io/wildfly/wildfly-s2i-jdk11
    builderImage: quay.io/jfdenise/wildfly-s2i-jdk11
    #runtimeImage: quay.io/wildfly/wildfly-runtime-jre11
    runtimeImage: quay.io/jfdenise/wildfly-runtime-jre11
  output:
    kind: "ImageStreamTag"
  triggers: {}
deploy:
  enabled: true
  replicas: 1
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin