{{- define "wildfly-common.deployment.tpl" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "wildfly-common.appName" . }}
  labels: {}
  annotations:
  {{- if and .Values.build.enabled (eq .Values.build.output.kind "ImageStreamTag") }}
    image.openshift.io/triggers: |-
      [
        {
          "from":{
            "kind":"ImageStreamTag",
            "name":"{{ include "wildfly-common.appImage" . }}"
          },
          "fieldPath":"spec.template.spec.containers[0].image"
        }
      ]
  {{- end }}
  {{- if and .Values.build.enabled .Values.build.uri }}
    app.openshift.io/vcs-uri:  {{ quote .Values.build.uri }}
  {{- end }}
  {{- if and .Values.build.enabled .Values.build.ref }}
    app.openshift.io/vcs-ref:  {{ quote .Values.build.ref }}
  {{- end }}
  {{- if .Values.deploy.annotations }}
    {{- tpl (toYaml .Values.deploy.annotations) . | nindent 4 }}
  {{- end }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      {{- include "wildfly-common.selectorLabels" . | nindent 6 }}
  template:
      {{- include "wildfly-common.podtemplate" . | nindent 6 -}}
{{ end }}

{{- define "wildfly-common.deployment" -}}
{{- include "wildfly-common.util.merge" (append . "wildfly-common.deployment.tpl") -}}
{{- end -}}