name: Helm Chart Testing

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          node_image: "kindest/node:v1.27.3"
          config: ./testing/kind-config.yaml

      - name: Setup Image registry
        run: |-
          ./testing/setup-image-registry.sh

      - name: Setup Nginx Ingress Controller
        run: |-
          ./testing/setup-nginx-ingress-controller.sh

      - name: Run Ingress Tests
        run: |-
          cd testing/ingress
          ./test.sh

